//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIACore.Website.ITUserByEmail {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ws.ups.com", ConfigurationName="ITUserByEmail.UserMailboxPort")]
    public interface UserMailboxPort {
        
        // CODEGEN: Generating message contract since the operation getUserMailbox is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BIACore.Website.ITUserByEmail.getUserMailboxResponse getUserMailbox(BIACore.Website.ITUserByEmail.getUserMailboxRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="ws.ups.com")]
    public partial class UserMailboxRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string appkeyField;
        
        private string mailboxIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string appkey {
            get {
                return this.appkeyField;
            }
            set {
                this.appkeyField = value;
                this.RaisePropertyChanged("appkey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MailboxID {
            get {
                return this.mailboxIDField;
            }
            set {
                this.mailboxIDField = value;
                this.RaisePropertyChanged("MailboxID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ws.ups.com")]
    public partial class UserMailboxRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uuidField;
        
        private string empidField;
        
        private string racfidField;
        
        private string lastnameField;
        
        private string firstnameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string empid {
            get {
                return this.empidField;
            }
            set {
                this.empidField = value;
                this.RaisePropertyChanged("empid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string racfid {
            get {
                return this.racfidField;
            }
            set {
                this.racfidField = value;
                this.RaisePropertyChanged("racfid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
                this.RaisePropertyChanged("lastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
                this.RaisePropertyChanged("firstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ws.ups.com")]
    public partial class UserMailboxResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private int countField;
        
        private UserMailboxRecord[] recordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("record", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public UserMailboxRecord[] record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("record");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserMailboxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="ws.ups.com", Order=0)]
        public BIACore.Website.ITUserByEmail.UserMailboxRequest UserMailboxRequest;
        
        public getUserMailboxRequest() {
        }
        
        public getUserMailboxRequest(BIACore.Website.ITUserByEmail.UserMailboxRequest UserMailboxRequest) {
            this.UserMailboxRequest = UserMailboxRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserMailboxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="ws.ups.com", Order=0)]
        public BIACore.Website.ITUserByEmail.UserMailboxResult result;
        
        public getUserMailboxResponse() {
        }
        
        public getUserMailboxResponse(BIACore.Website.ITUserByEmail.UserMailboxResult result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserMailboxPortChannel : BIACore.Website.ITUserByEmail.UserMailboxPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserMailboxPortClient : System.ServiceModel.ClientBase<BIACore.Website.ITUserByEmail.UserMailboxPort>, BIACore.Website.ITUserByEmail.UserMailboxPort {
        
        public UserMailboxPortClient() {
        }
        
        public UserMailboxPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserMailboxPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserMailboxPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserMailboxPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BIACore.Website.ITUserByEmail.getUserMailboxResponse BIACore.Website.ITUserByEmail.UserMailboxPort.getUserMailbox(BIACore.Website.ITUserByEmail.getUserMailboxRequest request) {
            return base.Channel.getUserMailbox(request);
        }
        
        public BIACore.Website.ITUserByEmail.UserMailboxResult getUserMailbox(BIACore.Website.ITUserByEmail.UserMailboxRequest UserMailboxRequest) {
            BIACore.Website.ITUserByEmail.getUserMailboxRequest inValue = new BIACore.Website.ITUserByEmail.getUserMailboxRequest();
            inValue.UserMailboxRequest = UserMailboxRequest;
            BIACore.Website.ITUserByEmail.getUserMailboxResponse retVal = ((BIACore.Website.ITUserByEmail.UserMailboxPort)(this)).getUserMailbox(inValue);
            return retVal.result;
        }
    }
}
