//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flote.WebAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://BIAFTPV.UPS.COM")]
        public string FTPFilePathDev {
            get {
                return ((string)(this["FTPFilePathDev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://ftp2.ups.com")]
        public string FTPFilePathProd {
            get {
                return ((string)(this["FTPFilePathProd"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BIA_FTP_FLOTE")]
        public string FTPUserIdDev {
            get {
                return ((string)(this["FTPUserIdDev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEC_BIA_FTP_FLOTE_2021")]
        public string FTPUserPSWDev {
            get {
                return ((string)(this["FTPUserPSWDev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eracapo0910")]
        public string FTPUserIdEMEA {
            get {
                return ((string)(this["FTPUserIdEMEA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("liteRature*1741impUl5e_85382024#")]
        public string FTPUserPSWEMEA {
            get {
                return ((string)(this["FTPUserPSWEMEA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eracapo0910")]
        public string FTPUserIdZA {
            get {
                return ((string)(this["FTPUserIdZA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("liteRature*1741impUl5e_85382024#")]
        public string FTPUserPSWZA {
            get {
                return ((string)(this["FTPUserPSWZA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2eracp0910")]
        public string FTPUserIdAPAC {
            get {
                return ((string)(this["FTPUserIdAPAC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B1ZGYc@vsK6W&5TuvuJ8&#nA4-A?=xx9")]
        public string FTPUserPSWAPAC {
            get {
                return ((string)(this["FTPUserPSWAPAC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eracapo0910")]
        public string FTPUserIdAmerica {
            get {
                return ((string)(this["FTPUserIdAmerica"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("liteRature*1741impUl5e_85382024#")]
        public string FTPUserPSWAmerica {
            get {
                return ((string)(this["FTPUserPSWAmerica"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eracapp0910")]
        public string FTPUserIdNAmerica {
            get {
                return ((string)(this["FTPUserIdNAmerica"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pLace_48376280Fxyl0pH0ne-778974#")]
        public string FTPUserPSWNAmerica {
            get {
                return ((string)(this["FTPUserPSWNAmerica"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtpapps-win.us.ups.com")]
        public string SMTPServer {
            get {
                return ((string)(this["SMTPServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BIA_FTP_FLOTE_BATCH")]
        public string FTPUserIdBatchDev {
            get {
                return ((string)(this["FTPUserIdBatchDev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEC_BIA_FTP_FLOTE_BATCH_2019")]
        public string FTPUserPSWBatchDev {
            get {
                return ((string)(this["FTPUserPSWBatchDev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://BIAFTPV.UPS.COM")]
        public string FTPFilePathFloteBatchDev {
            get {
                return ((string)(this["FTPFilePathFloteBatchDev"]));
            }
        }
    }
}
