//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIACore.Website.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogActivity {
            get {
                return ((bool)(this["LogActivity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BIA_FTP_TEP")]
        public string MyReportsUser {
            get {
                return ((string)(this["MyReportsUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExternalSecurity {
            get {
                return ((bool)(this["ExternalSecurity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/bia/apps/BIASecurity/unsecure/index.cfm")]
        public string ExternalSecurityLogin {
            get {
                return ((string)(this["ExternalSecurityLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/bia/CustomTag/BIA_Logout.cfm")]
        public string ExternalSecurityLogout {
            get {
                return ((string)(this["ExternalSecurityLogout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U2FsZXM4NTVzZWNyZXQu")]
        public string RouterKey {
            get {
                return ((string)(this["RouterKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""ConnectionName"":""Security"",""ServerName"":""CSVP000585C7"",""InstanceName"":""WWBIAC03E018"",""ServerType"":""SQL"",""ServerVersion"":""2014"",""DatabaseName"":""Dasa_Guestbook"",""Provider"":""System.Data.SqlClient"",""IncludeProvider"":0,""Username"":""bia_security_app_dev"",""AuthKey"":""EncryptedString""}")]
        public string NewDefaultSecurityConnection {
            get {
                return ((string)(this["NewDefaultSecurityConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEC_BIA_FTP_TEP_2019")]
        public string MyReportsPass {
            get {
                return ((string)(this["MyReportsPass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp://BIAFTPV.UPS.COM/")]
        public string MyReportsPath {
            get {
                return ((string)(this["MyReportsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          {
          ""ConnectionName"":""NewSecurity"",""ServerName"":""CSVP000585C7"",""InstanceName"":""WWBIAC03E018"",""ServerType"":""SQL"",""ServerVersion"":""2014"",
          ""DatabaseName"":""BIASecurity"",""Provider"":""System.Data.SqlClient"",""Username"":""bia_security_app_dev"",
          ""AuthKey"":""000001aVEyAQACAAA=DTwL4xRhBuq+eNIes7F/pZ/O74A=""
          }
        ")]
        public string DefaultSecurityConnection {
            get {
                return ((string)(this["DefaultSecurityConnection"]));
            }
        }
    }
}
